### ISSUE TITLE
Not correct time of Qualifying session

### ISSUE THREAD

**Issue by bolyaolya** [jolpica/jolpica-f1#68]
**Describe the bug**
In Race List - Netherlands weekend - mistake in Qualifying session. It should be 14:00:00Z

**Screenshots**
![image_2024-08-17_115129058](https://github.com/user-attachments/assets/f92a6edf-c712-40b3-bd57-365ad121e932)

**Comment by jolpica** [comment]
Thanks for reporting this, in future it'd really be appreciated if you could provide links.
jolpi.ca response: https://api.jolpi.ca/ergast/f1/2024/races.json?offset=14&limit=1
```
...
          "Qualifying": {
            "date": "2024-08-24",
            "time": "13:00:00Z"
          }
...
```
ergast response: https://ergast.com/api/f1/2024/races.json?offset=15&limit=1
```
...
          "Qualifying": {
            "date": "2024-08-31",
            "time": "14:00:00Z"
          }
...
```

At first glance looks like it could be a change in ergast data since the last import, will try another import tomorrow to see if its resolved.

**Comment by jolpica** [comment]
fixed: https://api.jolpi.ca/ergast/f1/2024/races.json?limit=1&offset=14
